apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 958055464432.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 958055464432.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: be4b8241
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
